### PR TITLE
convert to requireable package

### PR DESCRIPTION
**Pull request by swflint**
This should make the package something you can use `require` with.  It also starts to make some other minor changes in style.

### CODE REVIEW

**Comment by justintaft** [comment]
Thanks for the PR! Can you replace "org-split-clock-split-time"  to "org-split-clock-entry"? I think it's more fitting. Will merge the PR after 👍.

**Comment by swflint** [comment]
Done.  Please make sure to a) run checkdoc on the package, you'll likely have information you want put in there specifically, and b) use the melpa style checker so you can get it in MELPA.

**Comment by alphapapa** [comment]
Don't forget lexical-binding.  :)

**Comment by justintaft** [comment]
Created a recipe and create a PR to melpa. Hopefully otherwise will find this useful!

https://github.com/melpa/melpa/pull/5723

**Pull request merged**
